apiVersion: v1
kind: Service
metadata:
  name: example-api-service
spec:
  selector:
    app: app
  ports:
    - name: name-of-service-port
      protocol: TCP
      port: 4040
      targetPort: http-web-svc