apiVersion: v1
kind: Pod
metadata:
  name: example-api
  labels:
    app: app
spec:
  containers:
    - name: api
      image: kawwik/example-api:latest
      ports:
        - containerPort: 4000
      volumeMounts:
        - name: config
          mountPath: "/api/config"
          readOnly: true
  volumes:
    - name: config
      configMap:
        name: feature-flags