apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-deployment
  labels:
    app: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: kawwik/example-api:latest
          ports:
            - containerPort: 4000
          volumeMounts:
            - name: config
              mountPath: "/api/config"
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: feature-flags